### ISSUE TITLE
Input sequence with padding

### ISSUE THREAD

**Issue by cyrilli** [maxjcohen/transformer#11]
Thanks for sharing this project! I have a question regarding inputs with padding.

In my dataset, the sequences have different length, so I had to pad / truncate them to the same length K. I use zero vectors for the padded positions, which means in some input sequences (K, d_input), some vectors (of size d_input) on the left end are zero vectors.

Ideally, I'd hope that those padded positions won't affect the loss, or get involved in the computation of subsequent non-padded positions. After looking at your code it seems the current implementation can not guarantee this. If we add position embedding to the zero vectors, they will have non-zero values, and therefore affect loss and computation of subsequent positions.

Please correct me if I am wrong. I am not quite familiar with PyTorch. Is there any easy fix for masking those padded positions?

**Comment by maxjcohen** [comment]
Hi, thanks for taking an interest in this project.

The padding process is fairly common, used in particular in computer vision, without taking much precaution. To this day, I have yet to see a single paper highlighting zero padding as a limitation for converging.

That being said, let's say you want to make absolutely sure your zero padding don't affect your loss, the most Transformer-related method I can think of would involves using the score matrix. By setting the score to `0` where you added padding, you could completely shut off part of the input sequence. See [this part of the code](https://github.com/maxjcohen/transformer/blob/master/tst/multiHeadAttention.py#L94) for an example off applying a local window to the score matrix.

Positional Encodings are currently disabled by default on this repo, they should not be an issue in your case.

**Comment by cyrilli** [comment]
Thanks!
