### ISSUE TITLE
the transformer to be applied to classification

### ISSUE THREAD

**Issue by hongjianyuan** [maxjcohen/transformer#18]
How should I change the transformer to be applied to classification, such as seq2seq (many to many), how should I change it in the last layer of the model

**Comment by maxjcohen** [comment]
Hi, I believe the most straight forward solution would be to keep the original architecture, and only change the [output module](https://github.com/maxjcohen/transformer/blob/master/tst/transformer.py#L145). Currently, I have a linear transformation followed by a sigmoid activation, I would start by simply replacing the activation with a softmax, and see from there.

**Comment by hongjianyuan** [comment]
I currently want to input 250 features, segment them, and output the categories of these 250 features, so I just need to change the output module to softmax?

**Comment by maxjcohen** [comment]
Yes, set `d_input=250`, `d_ouptut` to the number of class, and replace the sigmoid by a softmax, you should have a functional segmentation algorithm.

**Comment by hongjianyuan** [comment]
Thank you very much

**Comment by hongjianyuan** [comment]
Hello, I still have a question, I use 2500*1 data, but I want to make a sliding window, the window size is 250*1, so my input is [1,250,1]? k is 250? Or I only need to enter [1, 2500, 1], transformer can help with the steps of sliding window, thank you

**Comment by hongjianyuan** [comment]
> 是的，设置`d_input=250`，`d_ouptut`上课的人数，并通过SOFTMAX更换乙状结肠，你应该有一个功能分割算法。

If it is the category of these 250 features, the output is like 250*4

**Comment by nurkbts** [comment]
Hello, when I run the code in my own dataset (14 feature + 1 label), I get this error when trained, can you help with this?


for idx_epoch in range(EPOCHS):
    running_loss = 0
    with tqdm(total=len(train_dl.dataset), desc=f"[Epoch {idx_epoch+1:3d}/{EPOCHS}]") as pbar:
      for idx_batch, (x, y) in enumerate(train_dl):
              # clear the gradients
        optimizer.zero_grad()
        yhat = net(x)------error

IndexError                                Traceback (most recent call last)
<ipython-input-134-338f7eaf9784> in <module>()
    228 '''
    229 # train the model
--> 230 train_model(train_dl, model)
    231 # evaluate the model
    232 acc = evaluate_model(test_dl, model)

6 frames
/content/multiHeadAttention.py in forward(self, query, key, value, mask)
     89 
     90         # Scaled Dot Product
---> 91         self._scores = torch.bmm(queries, keys.transpose(1, 2)) / np.sqrt(K)
     92 
     93         # Compute local map mask

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

**Comment by MJimitater** [comment]
Hi @maxjcohen , thanks for your great repo!

Is it possible to change the transformer to understand sequence classification (many-to-one)?

**Comment by maxjcohen** [comment]
Hi, nothing is stopping you from setting `d_output = 1`, in order for the Transformer to behave as a many-to-one model. In practice, every hidden state will be computed with a dimension `d_model`, and later aggregated in the last layer to output a single value. Note that this process in different from how traditional architectures, such as RNN based networks, handle many-to-one predictions.

**Comment by MJimitater** [comment]
Thank you for your reply @maxjcohen ! How exactly do you mean its different? From the way a RNN-model would take hidden states as further input?

**Comment by maxjcohen** [comment]
RNN carry a memory-like hidden state across time steps, while the Transformer has no notion of memory and compute time steps in parallel instead.
