### ISSUE TITLE
A more detailed Readme.

### ISSUE THREAD

**Issue by tcapelle** [maxjcohen/transformer#19]
Hello,
I am also interested on Transformers applied to TimeSeries, but I am having a hard time understanding the repo.
I would suggest adding more info to the Readme to show the capabilities of the library.
- Is it a forecasting model? multistep ahead, single step?
- Is it a classification model (as InceptionTime), can be adapted to do this?
- Is it a regression model?

I would also be nice to have a small graph like the ones on the training notebooks on the Readme, to show the potential.
Great work btw, and I am very interested to collaborate.
We run a Time Series Study group on the fast.ai forums:
- [Here](https://forums.fast.ai/t/time-series-sequential-data-study-group/29686) for V1 of the library (soon outdated) 
- [Here](https://forums.fast.ai/t/time-series-sequential-data-study-group/29686/658) for the updated V2 fastai library.

**Comment by maxjcohen** [comment]
Hi, the Transformer implemented in this repo is very similar to the original model described in _Attention Is All You Need_, I would suggest heading there for more information. To answer your questions,

- The Transformer is a coherent many to many model, i.e. we predict one single output for each input. Using the current architecture, it is not suited for forecasting
- We implemented this Transformer with regression in mind, but you should be able to apply it to classification, see for instance #18  (pinned for more visibility)

If you want to add some modules, or modify the model itself (for forcasting or classification for example), don't hesitate to fork and PR. And thanks for the links, I'll be sure to check them out !
