### ISSUE TITLE
Accuracy vs LSTM

### ISSUE THREAD

**Issue by mahdiabdollahpour** [maxjcohen/transformer#22]
Have you compared the results of Transformer vs LSTM in time series prediction?

**Comment by maxjcohen** [comment]
Hi, see [here](https://arxiv.org/abs/2006.12390) for a rough comparison (Table 1). In practice, RNN based models are faster when computing on longer sequences.

**Comment by mahdiabdollahpour** [comment]
> Hi, see [here](https://arxiv.org/abs/2006.12390) for a rough comparison (Table 1). In practice, RNN based models are faster when computing on longer sequences.

Thanks for the link to the paper. Did you do hyperparameter tuning for LSTM, BiGRU benchmarks, too? ( similar to grid search in table 7)

**Comment by maxjcohen** [comment]
No, we could not tune the HP for any model other than the Transformer, but they seem to be very promising. You should be able to get similar of better result from the BiGRU and ConvGru in particular, if you spend a little time tuning them.

I did not get the time to benchmark with a fully convolutional network (similar to wavenet approaches), but I believe it would yield very good results too, for a limited computation cost.
