### ISSUE TITLE
Is this implementation autoregressive for a seq2seq task?

### ISSUE THREAD

**Issue by shamoons** [maxjcohen/transformer#31]
I can't quite see where to pass inputs to the decoder. It seems to just copy the encoder inputs?

**Comment by maxjcohen** [comment]
Hi, I didn't plan to pass inputs directly to the decoder. Currently, it takes as input the latent vector, computed by the encoder. See [these lines](https://github.com/maxjcohen/transformer/blob/master/tst/transformer.py#L129-L143).
