### ISSUE TITLE
can you explain more on dimension arguments to transformer class ?

### ISSUE THREAD

**Issue by shivaniarbat** [maxjcohen/transformer#46]
`d_model` here is output encoding dimension from the positional encoding. What is `d_input` and `d_output` ? shouldn't the value be **1** for both variables ? <br>

`    d_input  : Model input dimension.`
`     d_model : Dimension of the input vector.`
`     d_output: Model output dimension.`

Can you explain this in relation to original paper ? (the application here to time-series )

**Comment by maxjcohen** [comment]
Hi, here we have

- `d_intput`: dimension of the input vector. For NLP task, this would be the dimension of your embedding space. For time series, in the examples you can find in the documentation, I use about 30 variables as input.
- `d_model`: dimension of the latent vector. This corresponds to the `d_model` in the original paper.
- `d_output`: dimension of the output vector.
