### ISSUE TITLE
Citation Bibtex

### ISSUE THREAD

**Issue by MJimitater** [maxjcohen/transformer#48]
Hi @maxjcohen, great application, thank you!

Im wondering, what citation (preferably bibtex) can I use in order to cite your work?

**Comment by maxjcohen** [comment]
Hi, you can use this citation:

```
@article{Cohen2020EndtoendDM,
  title={End-to-end deep metamodeling to calibrate and optimize energy loads},
  author={Max Cohen and M. Charbit and Sylvain Le Corff and M. Preda and Gilles Noziere},
  journal={ArXiv},
  year={2020},
  volume={abs/2006.12390}
}
```

The paper will be published in Building & Energy in about a month, I'll update the citation then. You can find the pdf here (the arXiv version is not up to date for some obscure reason).
[metamodel_arxiv.pdf](https://github.com/maxjcohen/transformer/files/6413428/metamodel_arxiv.pdf)

**Comment by MJimitater** [comment]
Thanks  @maxjcohen 👍

**Comment by maxjcohen** [comment]
Hi @MJimitater, I've updated the citation.
