### ISSUE TITLE
Can time series A be used to predict time series B？

### ISSUE THREAD

**Issue by chuzheng88** [maxjcohen/transformer#53]
I have read the docs of this github project. In some notebook, I found that time series A was used to predict time series B. I want to know that the Transformer proposed in this project could use time series A to predict time series B.

**Comment by maxjcohen** [comment]
Hi, yes it can. It actually for this kind of application this model was designed.

**Comment by chuzheng88** [comment]
Oh, I'm so sorry, my question was writen wrong. The right question is described as follows:

In some notebook, I found that time series A was used to predict the same time series A. I want to know that the Transformer proposed in this project could use time series A to predict time series B.

In addition, I want to use your project code to deal with a regression problem, and it is described as follows:
X =
[
[[time series sequence 1]],
[[time series sequence 2]],
***
[[time series sequence s]],
]
and y = [
[[label 1]],
[[label 2]],
***
[[label s]],
]
where sequences are not the same length.
So I want to just use your model definition ([transformer.py](https://github.com/maxjcohen/transformer/blob/master/tst/transformer.py)) and paddding all sequences to the same length in my dataset before input the model.

Is there any thing I need to pay attention to in this job ? Or do you have other suggestions ?

Thansk.

**Comment by chuzheng88** [comment]
> are you solve the problem?

No
