### ISSUE TITLE
How do I set d_model, q, v, h, N, dropout, attention_size value?

### ISSUE THREAD

**Issue by mmsx** [maxjcohen/transformer#56]
Hi, I have a question. If I want to use the transformer part to deal with my image datasets, the datasets from high to 256 pixels and width to 128 pixels images, images in each group have 3000 pieces, how do I set d_model, q, v, h, N, dropout, attention_size value?

**Comment by maxjcohen** [comment]
Hi, this repo is focused on applying the Transformer for time series modelling. While you technically could use our implementation for computer vision, there are better Transformer implementations for this use case.
