### ISSUE TITLE
The input dimension???

### ISSUE THREAD

**Issue by YangJoy750** [maxjcohen/transformer#57]
if my input dimension is 3, which means x.shape = [a,b,c] and my output is [a], what changes I need to do to fit the data?

**Comment by maxjcohen** [comment]
Hi, please see the [documentation](https://timeseriestransformer.readthedocs.io/en/latest/transformer.html) for information regarding the shape of input and output tensors, as well as the examples in the repo.

**Comment by YangJoy750** [comment]
yeah, i have seen it, but when I fit my own data, it has some problems about it. Could you tell me the input and output dimension of original data?(I can't download it, so sad), thanks a lot

**Comment by maxjcohen** [comment]
As written in the docs, the shape of the input tensor should be `(batch_size, K, d_input)` (where `K` is the number of time steps), and the output tensor should be `(batch_size, K, d_output)`.

**Comment by YangJoy750** [comment]
Actually, my input shape is [3000,20,5], and output shape is [1]. I try to use the model in time series prediction. [3000,20,5] means I have 3000 sequences, which have 5 features, and the length of each sequence is 20. and I want to predict the tomorrow data(so that the output shape is 1), what should I change to fit?

**Comment by maxjcohen** [comment]
The transformer, at least the implementation of this repo, focuses on sequence to sequence predictions. In other terms, it's probably not a good fit for your data ; I would take a look at more traditional architectures such as RNNs if you didn't already. However, if you really wish to use this transformer, you could simply add a fully connected layer following the Transformer model, in order to output a single value as in your data.

**Comment by YangJoy750** [comment]
oh, sorry about that, the output dimension is [3000], one sequence predicts a single value finally, can I regard each output is a sequence which length is 1, so I can use the model?

**Comment by maxjcohen** [comment]
This Transformer expects both input and output sequences to have the same number of time steps. But again, you can always add a fully connected layer after the Transformer layer in order to predict a single value for each sequence.

**Comment by YangJoy750** [comment]
I see, thanks a lot!

**Comment by maxjcohen** [comment]
Yes this is correct.
