### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by chuzheng88** [maxjcohen/transformer#58]
![image](https://user-images.githubusercontent.com/17675722/188263522-fa009bee-68a8-4f6a-a9df-cec0d85ddb25.png)

why did the error occur ?

**Comment by maxjcohen** [comment]
Hi, please take a minute to read the [documentation](https://timeseriestransformer.readthedocs.io/en/latest/transformer.html). The shape of the input tensor should be `(batch_size, sequence_length, input_dimension)`, so in your case `(batch_size, 1000, 2)`.

**Comment by chuzheng88** [comment]
![image](https://user-images.githubusercontent.com/17675722/188264968-d67857dd-728b-4db1-8d39-bd1a37cf6f32.png)

also error occur

**Comment by maxjcohen** [comment]
Again, *please read the [documentation of `MultiHeadAttentionChunk`](https://timeseriestransformer.readthedocs.io/en/latest/multiHeadAttention.html#multiHeadAttention.MultiHeadAttentionChunk)*. You're using the `Chunk` MHA, which clearly states that the default `chunk_size` is `168`. This is why you are getting an error.
