### ISSUE TITLE
How to set Positional encoding

### ISSUE THREAD

**Issue by flydephone** [maxjcohen/transformer#59]
I have a time-series dataset with day-scale resolution.
When I set the ```pe = 'regular'  # Positional encoding```,
Then I will get an error ```TypeError: generate_original_PE() got an unexpected keyword argument 'period```
So I can only use the ```regular``` PE, but I don't know how to set the ```pe_period```. It seems that a ```pe_period = 24``` are for dataset with Hour-scale resolution.

**Comment by maxjcohen** [comment]
Hi, thanks for reporting this issue, it should be fixed with 997b08e18fc06452a505d14c39f33294b4d9e65e.

**Comment by flydephone** [comment]
Thanks. By the way, I still want to know how to set the ```pe_period``` when I use the ```regular``` PE.

**Comment by maxjcohen** [comment]
I haven't gotten around to code this setting, fell free to send a PR if you've got the time to write it yourself. The function is defined here:
https://github.com/maxjcohen/transformer/blob/997b08e18fc06452a505d14c39f33294b4d9e65e/tst/utils.py#L7-L29

**Comment by flydephone** [comment]
OK, I will figure out it.
