### ISSUE TITLE
 Run out of memory 

### ISSUE THREAD

**Issue by SheldonLiu0412** [maxjcohen/transformer#65]
How much memory is required for training in the default configuration? 
 16G？32G？more？

**Comment by maxjcohen** [comment]
Hi, there is no default configuration, I experimented with multiple sizes and model layouts in my experiments. However, they all ran on my old laptop with 8G of RAM and 2G VRAM.

**Comment by SheldonLiu0412** [comment]
<img width="448" alt="image" src="https://github.com/user-attachments/assets/7384fa36-25da-4ab0-9ed6-5dc7223481d4">
Hello, I have been constantly getting low memory alerts, even though I have 32GB of memory.Did the code encounter any errors during execution?

**Comment by maxjcohen** [comment]
Hi, like I said, the amount of memory required depends on the size of the model you build. If you run out of memory, try to reduce the number of layers (`N`) or the dimension of the latent spaces (`d_model`, `q`, `k`, `v` or `h`).
